Breed.create family: 'cat', title_en: 'Abyssinian', title_ru: 'Абиссинская'
Breed.create family: 'cat', title_en: 'Australian_Mist', title_ru: 'Австралийская дымчатая'
Breed.create family: 'cat', title_en: 'Australian_Tiffanie', title_ru: 'Австралийская тиффани'
Breed.create family: 'cat', title_en: 'Asian_Longhair', title_ru: 'Азиатская длинношерстная (Тиффани)'
Breed.create family: 'cat', title_en: 'Asian_Smoke', title_ru: 'Азиатская дымчатая'
Breed.create family: 'cat', title_en: 'Asian_Shorthair', title_ru: 'Азиатская короткошерстная'
Breed.create family: 'cat', title_en: 'Asian_Tabby', title_ru: 'Азиатская табби'
Breed.create family: 'cat', title_en: 'American_Wirehair', title_ru: 'Американская жесткошерстная'
Breed.create family: 'cat', title_en: 'American_Ringtail', title_ru: 'Американская кольцехвостая'
Breed.create family: 'cat', title_en: 'American_Shorthair', title_ru: 'Американская короткошерстная'
Breed.create family: 'cat', title_en: 'American_Bobtail', title_ru: 'Американский бобтейл'
Breed.create family: 'cat', title_en: 'American_Curl', title_ru: 'Американский кёрл'
Breed.create family: 'cat', title_en: 'Anatoli', title_ru: 'Анатолийская'
Breed.create family: 'cat', title_en: 'Arabian_Mau', title_ru: 'Аравийский мау'
Breed.create family: 'cat', title_en: 'Balinese', title_ru: 'Балинезийская (балинез)'
Breed.create family: 'cat', title_en: 'Bengal', title_ru: 'Бенгальская короткошерстная (Бенгал)'
Breed.create family: 'cat', title_en: 'Birman', title_ru: 'Бирманская'
Breed.create family: 'cat', title_en: 'Bohemia_Rex', title_ru: 'Богемский рекс'
Breed.create family: 'cat', title_en: 'Bombay', title_ru: 'Бомбейская (Бомбей)'
Breed.create family: 'cat', title_en: 'Brazilian_Shorthair', title_ru: 'Бразильская короткошерстная'
Breed.create family: 'cat', title_en: 'Bristol', title_ru: 'Бристоль'
Breed.create family: 'cat', title_en: 'British_Longhair', title_ru: 'Британская длинношерстная'
Breed.create family: 'cat', title_en: 'British_Shorthair', title_ru: 'Британская короткошерстная'
Breed.create family: 'cat', title_en: 'Burmese', title_ru: 'Бурмезская короткошерстная (бурма)'
Breed.create family: 'cat', title_en: 'Burmilla', title_ru: 'Бурмилла'
Breed.create family: 'cat', title_en: 'Havana_Brown', title_ru: 'Гавана браун'
Breed.create family: 'cat', title_en: 'German_Rex', title_ru: 'Герман рекс (Немецкий рекс)'
Breed.create family: 'cat', title_en: 'Devon_Rex', title_ru: 'Девон-рекс'
Breed.create family: 'cat', title_en: 'Domestic_cat', title_ru: 'Домашняя кошка'
Breed.create family: 'cat', title_en: 'Don_Sphynx', title_ru: 'Донской сфинкс'
Breed.create family: 'cat', title_en: 'European_SH', title_ru: 'Европейская КШ (Кельтская)'
Breed.create family: 'cat', title_en: 'Egyptian_Mau', title_ru: 'Египетская мау'
Breed.create family: 'cat', title_en: 'Foreign_White', title_ru: 'Иностранная Белая'
Breed.create family: 'cat', title_en: 'York_Chocolate', title_ru: 'Йорк (Йоркская шоколадная)'
Breed.create family: 'cat', title_en: 'California_Spangled', title_ru: 'Калифорнийская сияющая'
Breed.create family: 'cat', title_en: 'Kanaani', title_ru: 'Канаани (Ханаани)'
Breed.create family: 'cat', title_en: 'Karelian_Bobtail', title_ru: 'Карельский бобтейл'
Breed.create family: 'cat', title_en: 'Cymric', title_ru: 'Кимрик (длинношерстный манкс)'
Breed.create family: 'cat', title_en: 'Chinese_Li_Hua', title_ru: 'Китайская Ли Hua'
Breed.create family: 'cat', title_en: 'Korat', title_ru: 'Корат'
Breed.create family: 'cat', title_en: 'Cornish_Rex', title_ru: 'Корниш-рекс'
Breed.create family: 'cat', title_en: 'Kurilian_Bobtail', title_ru: 'Курильский бобтейл'
Breed.create family: 'cat', title_en: 'LaPerm', title_ru: 'Лаперм'
Breed.create family: 'cat', title_en: 'Mandalay', title_ru: 'Мандалай (Мандалэй)'
Breed.create family: 'cat', title_en: 'Munchkin', title_ru: 'Манчкин'
Breed.create family: 'cat', title_en: 'Maine_Coon', title_ru: 'Мейн-кун'
Breed.create family: 'cat', title_en: 'Mekong_Bobtail', title_ru: 'Меконгский бобтейл'
Breed.create family: 'cat', title_en: 'Manx', title_ru: 'Мэнская безхвостая (Манкс)'
Breed.create family: 'cat', title_en: 'Neva_Masquerade', title_ru: 'Невская маскарадная'
Breed.create family: 'cat', title_en: 'Nebelung', title_ru: 'Нибелунг'
Breed.create family: 'cat', title_en: 'Norwegian_Forest', title_ru: 'Норвежская лесная'
Breed.create family: 'cat', title_en: 'Oriental_Shorthair', title_ru: 'Ориентальная короткошерстная'
Breed.create family: 'cat', title_en: 'Ojos_Azules', title_ru: 'Охос Азулес'
Breed.create family: 'cat', title_en: 'Ocicat', title_ru: 'Оцикет'
Breed.create family: 'cat', title_en: 'Persian', title_ru: 'Персидская'
Breed.create family: 'cat', title_en: 'Peterbald', title_ru: 'Петерболд (Петербургский сфинкс)'
Breed.create family: 'cat', title_en: 'Pixiebob', title_ru: 'Пиксибоб'
Breed.create family: 'cat', title_en: 'Poodle_Cat', title_ru: 'Пуделькэт'
Breed.create family: 'cat', title_en: 'Ragamuffin', title_ru: 'Рагамаффин'
Breed.create family: 'cat', title_en: 'Russian_Blue', title_ru: 'Русская голубая'
Breed.create family: 'cat', title_en: 'Ragdoll', title_ru: 'Рэгдолл'
Breed.create family: 'cat', title_en: 'Savannah', title_ru: 'Саванна'
Breed.create family: 'cat', title_en: 'Selkirk_Rex', title_ru: 'Селкирк-рекс'
Breed.create family: 'cat', title_en: 'Serengeti', title_ru: 'Серенгети'
Breed.create family: 'cat', title_en: 'Siamese', title_ru: 'Сиамская'
Breed.create family: 'cat', title_en: 'Siberian', title_ru: 'Сибирская'
Breed.create family: 'cat', title_en: 'Singapura', title_ru: 'Сингапура'
Breed.create family: 'cat', title_en: 'Scottish_Straight', title_ru: 'Скоттиш страйт'
Breed.create family: 'cat', title_en: 'Scottish_Fold_LH', title_ru: 'Скоттиш фолд  длинношерстный (Хайленд-фолд)'
Breed.create family: 'cat', title_en: 'Scottish_Fold_SH', title_ru: 'Скоттиш фолд  короткошерстный'
Breed.create family: 'cat', title_en: 'Snowshoe', title_ru: 'Сноу-шу'
Breed.create family: 'cat', title_en: 'Somali', title_ru: 'Сомали (Абиссинская ДШ)'
Breed.create family: 'cat', title_en: 'Sokoke', title_ru: 'Соукок'
Breed.create family: 'cat', title_en: 'Sphynx', title_ru: 'Сфинкс (Канадский сфинкс)'
Breed.create family: 'cat', title_en: 'Thai', title_ru: 'Тайская'
Breed.create family: 'cat', title_en: 'Tiffany', title_ru: 'Тиффани'
Breed.create family: 'cat', title_en: 'Toy-Bobtail', title_ru: 'Тойбоб, Скиф-тай-той-Дон'
Breed.create family: 'cat', title_en: 'Toyger', title_ru: 'Тойгер'
Breed.create family: 'cat', title_en: 'Tonkinese', title_ru: 'Тонкинская'
Breed.create family: 'cat', title_en: 'Turkish_Angora', title_ru: 'Турецкая ангора'
Breed.create family: 'cat', title_en: 'Turkish_Van', title_ru: 'Турецкий ван'
Breed.create family: 'cat', title_en: 'Ural_Rex', title_ru: 'Уральский рекс'
Breed.create family: 'cat', title_en: 'Ussuri', title_ru: 'Уссурийская КШ (Уссури)'
Breed.create family: 'cat', title_en: 'Ceylon', title_ru: 'Цейлонская'
Breed.create family: 'cat', title_en: 'Chausie', title_ru: 'Чаузи (Шаузи, Хаузи)'
Breed.create family: 'cat', title_en: 'Chartreux', title_ru: 'Шартрез'
Breed.create family: 'cat', title_en: 'Exotic_Shorthair', title_ru: 'Экзотическая короткошерстная'
Breed.create family: 'cat', title_en: 'Javanese', title_ru: 'Яванская (яванез)'
Breed.create family: 'cat', title_en: 'Japanese_Bobtail', title_ru: 'Японский бобтейл'
