Country.create id: 219, name_ru: 'Россия', name_en: 'Russia'
Country.create id: 220, name_ru: 'Украина', name_en:  'Ukraine'
Country.create id: 221, name_ru: 'Беларусь', name_en:  'Belarus'
Country.create id: 222, name_ru: 'Казахстан', name_en:  'Kazakhstan'
Country.create id: 223, name_ru: 'Германия', name_en:  'Germany'
Country.create id: 224, name_ru: 'Абхазия', name_en:  'Abkhazia'
Country.create id: 225, name_ru: 'Австралия', name_en:  'Australia'
Country.create id: 226, name_ru: 'Австрия', name_en:  'Austria'
Country.create id: 227, name_ru: 'Азербайджан', name_en:  'Azerbaijan'
Country.create id: 228, name_ru: 'Албания', name_en:  'Albania'
Country.create id: 229, name_ru: 'Алжир', name_en:  'Algeria'
Country.create id: 230, name_ru: 'Ангола', name_en:  'Angola'
Country.create id: 231, name_ru: 'Ангуилья', name_en:  'Anguilla'
Country.create id: 232, name_ru: 'Андорра', name_en:  'Andorra'
Country.create id: 233, name_ru: 'Антигуа и Барбуда', name_en:  'Antigua and Barbuda'
Country.create id: 234, name_ru: 'Антильские о-ва', name_en:  'Netherlands Antilles'
Country.create id: 235, name_ru: 'Аргентина', name_en:  'Argentina'
Country.create id: 236, name_ru: 'Армения', name_en:  'Armenia'
Country.create id: 237, name_ru: 'Арулько', name_en:  'Aruba'
Country.create id: 238, name_ru: 'Афганистан', name_en:  'Afghanistan'
Country.create id: 239, name_ru: 'Багамские о-ва', name_en:  'Bahamas'
Country.create id: 240, name_ru: 'Бангладеш', name_en:  'Bangladesh'
Country.create id: 241, name_ru: 'Барбадос', name_en:  'Barbados'
Country.create id: 242, name_ru: 'Бахрейн', name_en:  'Bahrain'
Country.create id: 243, name_ru: 'Белиз', name_en:  'Belize'
Country.create id: 244, name_ru: 'Бельгия', name_en:  'Belgium'
Country.create id: 245, name_ru: 'Бенин', name_en:  'Benin'
Country.create id: 246, name_ru: 'Бермуды', name_en:  'Bermuda'
Country.create id: 247, name_ru: 'Болгария', name_en:  'Bulgaria'
Country.create id: 248, name_ru: 'Боливия', name_en:  'Bolivia'
Country.create id: 249, name_ru: 'Босния/Герцеговина', name_en:  'Bosnia and Herzegovina'
Country.create id: 250, name_ru: 'Ботсвана', name_en:  'Botswana'
Country.create id: 251, name_ru: 'Бразилия', name_en:  'Brazil'
Country.create id: 252, name_ru: 'Британские Виргинские о-ва', name_en:  'British Virgin Islands'
Country.create id: 253, name_ru: 'Бруней', name_en:  'Brunei'
Country.create id: 254, name_ru: 'Буркина Фасо', name_en:  'Burkina Faso'
Country.create id: 255, name_ru: 'Бурунди', name_en:  'Burundi'
Country.create id: 256, name_ru: 'Бутан', name_en:  'Bhutan'
Country.create id: 257, name_ru: 'Валлис и Футуна о-ва', name_en:  'Wallis and Futuna'
Country.create id: 258, name_ru: 'Вануату', name_en:  'Vanuatu'
Country.create id: 259, name_ru: 'Великобритания', name_en:  'United Kingdom'
Country.create id: 260, name_ru: 'Венгрия', name_en:  'Hungary'
Country.create id: 261, name_ru: 'Венесуэла', name_en:  'Venezuela'
Country.create id: 262, name_ru: 'Восточный Тимор', name_en:  'East Timor'
Country.create id: 263, name_ru: 'Вьетнам', name_en:  'Vietnam'
Country.create id: 264, name_ru: 'Габон', name_en:  'Gabon'
Country.create id: 265, name_ru: 'Гаити', name_en:  'Haiti'
Country.create id: 266, name_ru: 'Гайана', name_en:  'Guyana'
Country.create id: 267, name_ru: 'Гамбия', name_en:  'Gambia'
Country.create id: 268, name_ru: 'Гана', name_en:  'Ghana'
Country.create id: 269, name_ru: 'Гваделупа', name_en:  'Guadeloupe'
Country.create id: 270, name_ru: 'Гватемала', name_en:  'Guatemala'
Country.create id: 271, name_ru: 'Гвинея', name_en:  'Guinea'
Country.create id: 272, name_ru: 'Гвинея-Бисау', name_en:  'Guinea-Bissau'
Country.create id: 273, name_ru: 'Гернси о-в', name_en:  'Guernsey'
Country.create id: 274, name_ru: 'Гибралтар', name_en:  'Gibraltar'
Country.create id: 275, name_ru: 'Гондурас', name_en:  'Honduras'
Country.create id: 276, name_ru: 'Гонконг', name_en:  'Hong Kong'
Country.create id: 277, name_ru: 'Гренада', name_en:  'Grenada'
Country.create id: 278, name_ru: 'Гренландия', name_en:  'Greenland'
Country.create id: 279, name_ru: 'Греция', name_en:  'Greece'
Country.create id: 280, name_ru: 'Грузия', name_en:  'Georgia'
Country.create id: 281, name_ru: 'Дания', name_en:  'Denmark'
Country.create id: 282, name_ru: 'Джерси о-в', name_en:  'Jersey'
Country.create id: 283, name_ru: 'Джибути', name_en:  'Djibouti'
Country.create id: 284, name_ru: 'Доминиканская республика', name_en:  'Dominican Republic'
Country.create id: 285, name_ru: 'Европы о-в', name_en:  'Europa Island'
Country.create id: 286, name_ru: 'Египет', name_en:  'Egypt'
Country.create id: 287, name_ru: 'Замбия', name_en:  'Zambia'
Country.create id: 288, name_ru: 'Западная Сахара', name_en:  'Western Sahara'
Country.create id: 289, name_ru: 'Зимбабве', name_en:  'Zimbabwe'
Country.create id: 290, name_ru: 'Израиль', name_en:  'Israel'
Country.create id: 291, name_ru: 'Индия', name_en:  'India'
Country.create id: 292, name_ru: 'Индонезия', name_en:  'Indonesia'
Country.create id: 293, name_ru: 'Иордания', name_en:  'Jordan'
Country.create id: 294, name_ru: 'Ирак', name_en:  'Iraq'
Country.create id: 295, name_ru: 'Иран', name_en:  'Iran'
Country.create id: 296, name_ru: 'Ирландия', name_en:  'Ireland'
Country.create id: 297, name_ru: 'Исландия', name_en:  'Iceland'
Country.create id: 298, name_ru: 'Испания', name_en:  'Spain'
Country.create id: 299, name_ru: 'Италия', name_en:  'Italy'
Country.create id: 300, name_ru: 'Йемен', name_en:  'Yemen'
Country.create id: 301, name_ru: 'Кабо-Верде', name_en:  'Cape Verde'
Country.create id: 302, name_ru: 'Камбоджа', name_en:  'Cambodia'
Country.create id: 303, name_ru: 'Камерун', name_en:  'Cameroon'
Country.create id: 304, name_ru: 'Канада', name_en:  'Canada'
Country.create id: 305, name_ru: 'Катар', name_en:  'Qatar'
Country.create id: 306, name_ru: 'Кения', name_en:  'Kenya'
Country.create id: 307, name_ru: 'Кипр', name_en:  'Cyprus'
Country.create id: 308, name_ru: 'Кирибати', name_en:  'Kiribati'
Country.create id: 309, name_ru: 'Китай', name_en:  'China'
Country.create id: 310, name_ru: 'Колумбия', name_en:  'Colombia'
Country.create id: 311, name_ru: 'Коморские о-ва', name_en:  'Comoros'
Country.create id: 312, name_ru: 'Конго (Brazzaville)', name_en:  'Congo (Brazzaville)'
Country.create id: 313, name_ru: 'Конго (Kinshasa)', name_en:  'Congo (Kinshasa)'
Country.create id: 314, name_ru: 'Коста-Рика', name_en:  'Costa Rica'
Country.create id: 315, name_ru: 'Кот-д''Ивуар', name_en:  'Cote D''Ivoire'
Country.create id: 316, name_ru: 'Куба', name_en:  'Cuba'
Country.create id: 317, name_ru: 'Кувейт', name_en:  'Kuwait'
Country.create id: 318, name_ru: 'Кука о-ва', name_en:  'Cook Islands'
Country.create id: 319, name_ru: 'Кыргызстан', name_en:  'Kyrgyzstan'
Country.create id: 320, name_ru: 'Лаос', name_en:  'Laos'
Country.create id: 321, name_ru: 'Латвия', name_en:  'Latvia'
Country.create id: 322, name_ru: 'Лесото', name_en:  'Lesotho'
Country.create id: 323, name_ru: 'Либерия', name_en:  'Liberia'
Country.create id: 324, name_ru: 'Ливан', name_en:  'Lebanon'
Country.create id: 325, name_ru: 'Ливия', name_en:  'Libya'
Country.create id: 326, name_ru: 'Литва', name_en:  'Lithuania'
Country.create id: 327, name_ru: 'Лихтенштейн', name_en:  'Liechtenstein'
Country.create id: 328, name_ru: 'Люксембург', name_en:  'Luxembourg'
Country.create id: 329, name_ru: 'Маврикий', name_en:  'Mauritius'
Country.create id: 330, name_ru: 'Мавритания', name_en:  'Mauritania'
Country.create id: 331, name_ru: 'Мадагаскар', name_en:  'Madagascar'
Country.create id: 332, name_ru: 'Македония', name_en:  'Macedonia'
Country.create id: 333, name_ru: 'Малави', name_en:  'Malawi'
Country.create id: 334, name_ru: 'Малайзия', name_en:  'Malaysia'
Country.create id: 335, name_ru: 'Мали', name_en:  'Mali'
Country.create id: 336, name_ru: 'Мальдивские о-ва', name_en:  'Maldives'
Country.create id: 337, name_ru: 'Мальта', name_en:  'Malta'
Country.create id: 338, name_ru: 'Мартиника о-в', name_en:  'Martinique'
Country.create id: 339, name_ru: 'Мексика', name_en:  'Mexico'
Country.create id: 340, name_ru: 'Мозамбик', name_en:  'Mozambique'
Country.create id: 341, name_ru: 'Молдова', name_en:  'Moldova'
Country.create id: 342, name_ru: 'Монако', name_en:  'Monaco'
Country.create id: 343, name_ru: 'Монголия', name_en:  'Mongolia'
Country.create id: 344, name_ru: 'Марокко', name_en:  'Morocco'
Country.create id: 345, name_ru: 'Мьянма (Бирма)', name_en:  'Myanmar (Burma)'
Country.create id: 346, name_ru: 'Мэн о-в', name_en:  'Isle of Man'
Country.create id: 347, name_ru: 'Намибия', name_en:  'Namibia'
Country.create id: 348, name_ru: 'Науру', name_en:  'Nauru'
Country.create id: 349, name_ru: 'Непал', name_en:  'Nepal'
Country.create id: 350, name_ru: 'Нигер', name_en:  'Niger'
Country.create id: 351, name_ru: 'Нигерия', name_en:  'Nigeria'
Country.create id: 352, name_ru: 'Нидерланды (Голландия)', name_en:  'Netherlands'
Country.create id: 353, name_ru: 'Никарагуа', name_en:  'Nicaragua'
Country.create id: 354, name_ru: 'Новая Зеландия', name_en:  'New Zealand'
Country.create id: 355, name_ru: 'Новая Каледония о-в', name_en:  'New Caledonia'
Country.create id: 356, name_ru: 'Норвегия', name_en:  'Norway'
Country.create id: 357, name_ru: 'Норфолк о-в', name_en:  'Norfolk Island'
Country.create id: 358, name_ru: 'О.А.Э.', name_en:  'United Arab Emirates'
Country.create id: 359, name_ru: 'Оман', name_en:  'Oman'
Country.create id: 360, name_ru: 'Пакистан', name_en:  'Pakistan'
Country.create id: 361, name_ru: 'Панама', name_en:  'Panama'
Country.create id: 362, name_ru: 'Папуа Новая Гвинея', name_en:  'Papua New Guinea'
Country.create id: 363, name_ru: 'Парагвай', name_en:  'Paraguay'
Country.create id: 364, name_ru: 'Перу', name_en:  'Peru'
Country.create id: 365, name_ru: 'Питкэрн о-в', name_en:  'Pitcairn Islands'
Country.create id: 366, name_ru: 'Польша', name_en:  'Poland'
Country.create id: 367, name_ru: 'Португалия', name_en:  'Portugal'
Country.create id: 368, name_ru: 'Пуэрто Рико', name_en:  'Puerto Rico'
Country.create id: 369, name_ru: 'Реюньон', name_en:  'Reunion'
Country.create id: 370, name_ru: 'Руанда', name_en:  'Rwanda'
Country.create id: 371, name_ru: 'Румыния', name_en:  'Romania'
Country.create id: 372, name_ru: 'США', name_en:  'United States'
Country.create id: 373, name_ru: 'Сальвадор', name_en:  'El Salvador'
Country.create id: 374, name_ru: 'Самоа', name_en:  'Samoa'
Country.create id: 375, name_ru: 'Сан-Марино', name_en:  'San Marino'
Country.create id: 376, name_ru: 'Сан-Томе и Принсипи', name_en:  'Sao Tome and Principe'
Country.create id: 377, name_ru: 'Саудовская Аравия', name_en:  'Saudi Arabia'
Country.create id: 378, name_ru: 'Свазиленд', name_en:  'Swaziland'
Country.create id: 379, name_ru: 'Святая Люсия', name_en:  'Saint Lucia'
Country.create id: 380, name_ru: 'Святой Елены о-в', name_en:  'Saint Helena'
Country.create id: 381, name_ru: 'Северная Корея', name_en:  'North Korea'
Country.create id: 382, name_ru: 'Сейшеллы', name_en:  'Seychelles'
Country.create id: 383, name_ru: 'Сен-Пьер и Микелон', name_en:  'Saint Pierre and Miquelon'
Country.create id: 384, name_ru: 'Сенегал', name_en:  'Senegal'
Country.create id: 385, name_ru: 'Сент Китс и Невис', name_en:  'Saint Kitts and Nevis'
Country.create id: 386, name_ru: 'Сент-Винсент и Гренадины', name_en:  'Saint Vincent and the Grenadines'
Country.create id: 387, name_ru: 'Сербия', name_en:  'Serbia'
Country.create id: 388, name_ru: 'Сингапур', name_en:  'Singapore'
Country.create id: 389, name_ru: 'Сирия', name_en:  'Syria'
Country.create id: 390, name_ru: 'Словакия', name_en:  'Slovakia'
Country.create id: 391, name_ru: 'Словения', name_en:  'Slovenia'
Country.create id: 392, name_ru: 'Соломоновы о-ва', name_en:  'Solomon Islands'
Country.create id: 393, name_ru: 'Сомали', name_en:  'Somalia'
Country.create id: 394, name_ru: 'Судан', name_en:  'Sudan'
Country.create id: 395, name_ru: 'Суринам', name_en:  'Suriname'
Country.create id: 396, name_ru: 'Сьерра-Леоне', name_en:  'Sierra Leone'
Country.create id: 397, name_ru: 'Таджикистан', name_en:  'Tajikistan'
Country.create id: 398, name_ru: 'Тайвань', name_en:  'Taiwan'
Country.create id: 399, name_ru: 'Таиланд', name_en:  'Thailand'
Country.create id: 400, name_ru: 'Танзания', name_en:  'Tanzania'
Country.create id: 401, name_ru: 'Того', name_en:  'Togo'
Country.create id: 402, name_ru: 'Токелау о-ва', name_en:  'Tokelau'
Country.create id: 403, name_ru: 'Тонга', name_en:  'Tonga'
Country.create id: 404, name_ru: 'Тринидад и Тобаго', name_en:  'Trinidad and Tobago'
Country.create id: 405, name_ru: 'Тувалу', name_en:  'Tuvalu'
Country.create id: 406, name_ru: 'Тунис', name_en:  'Tunisia'
Country.create id: 407, name_ru: 'Туркменистан', name_en:  'Turkmenistan'
Country.create id: 408, name_ru: 'Туркс и Кейкос', name_en:  'Turks and Caicos Islands'
Country.create id: 409, name_ru: 'Турция', name_en:  'Turkey'
Country.create id: 410, name_ru: 'Уганда', name_en:  'Uganda'
Country.create id: 411, name_ru: 'Узбекистан', name_en:  'Uzbekistan'
Country.create id: 412, name_ru: 'Уругвай', name_en:  'Uruguay'
Country.create id: 413, name_ru: 'Фарерские о-ва', name_en:  'Faroe Islands'
Country.create id: 414, name_ru: 'Фиджи', name_en:  'Fiji'
Country.create id: 415, name_ru: 'Филиппины', name_en:  'Philippines'
Country.create id: 416, name_ru: 'Финляндия', name_en:  'Finland'
Country.create id: 417, name_ru: 'Франция', name_en:  'France'
Country.create id: 418, name_ru: 'Французская Гвинея', name_en:  'French Guiana'
Country.create id: 419, name_ru: 'Французская Полинезия', name_en:  'French Polynesia'
Country.create id: 420, name_ru: 'Хорватия', name_en:  'Croatia'
Country.create id: 421, name_ru: 'Чад', name_en:  'Chad'
Country.create id: 422, name_ru: 'Черногория', name_en:  'Montenegro'
Country.create id: 423, name_ru: 'Чехия', name_en:  'Czech Republic'
Country.create id: 424, name_ru: 'Чили', name_en:  'Chile'
Country.create id: 425, name_ru: 'Швейцария', name_en:  'Switzerland'
Country.create id: 426, name_ru: 'Швеция', name_en:  'Sweden'
Country.create id: 427, name_ru: 'Шри-Ланка', name_en:  'Sri Lanka'
Country.create id: 428, name_ru: 'Эквадор', name_en:  'Ecuador'
Country.create id: 429, name_ru: 'Экваториальная Гвинея', name_en:  'Equatorial Guinea'
Country.create id: 430, name_ru: 'Эритрея', name_en:  'Eritrea'
Country.create id: 431, name_ru: 'Эстония', name_en:  'Estonia'
Country.create id: 432, name_ru: 'Эфиопия', name_en:  'Ethiopia'
Country.create id: 433, name_ru: 'ЮАР', name_en:  'South Africa'
Country.create id: 434, name_ru: 'Южная Корея', name_en:  'South Korea'
Country.create id: 435, name_ru: 'Южная Осетия', name_en:  'South Ossetia'
Country.create id: 436, name_ru: 'Ямайка', name_en:  'Jamaica'
Country.create id: 437, name_ru: 'Япония', name_en:  'Japan'
Country.create id: 438, name_ru: 'Макао', name_en:  'Macau'
